# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'RapidFund' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire', '~> 4.9.1'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'RxKeyboard'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  
  # Pods for RapidFund

  target 'RapidFundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RapidFundUITests' do
    # Pods for testing
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
        target.build_configurations.each do |config|

          if config.name == 'Test'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end

          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
        end
      end
    end
  end
end
